### ISSUE TITLE
Failed to load plugin descriptor

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/intellij-crystal#10]
Hi @TsundereBug I'm using your last zip file you published here :point_right: https://github.com/crystal-lang-tools/intellij-crystal/issues/1#issuecomment-320493153

But I'm getting this error:

![screenshot_20170905_074132](https://user-images.githubusercontent.com/3067335/30062427-bb975422-9210-11e7-8269-dddccac556f9.png)

My Intellij-idea version is:

![screenshot_20170905_080904](https://user-images.githubusercontent.com/3067335/30062669-96d07028-9211-11e7-8492-ae0e3eb2520d.png)

**Comment by s5bug** [comment]
Whichever zip you're using is incorrect, it didn't contain the descriptor file.

Try the Jar or the other Zip.

**Comment by faustinoaq** [comment]
Hi @TsundereBug I'm using this:

> EDIT: Whoops! That zip doesn't have any class files in it 😓 This one does 😄 
[intellij-crystal_jar.zip](https://github.com/intellij-crystal/intellij-crystal/files/1202962/intellij-crystal_jar.zip)

**Comment by s5bug** [comment]
Try the JAR file instead.

**Comment by faustinoaq** [comment]
Hi friend, can you give me a link? :sweat_smile:

**Comment by s5bug** [comment]
I might've deleted it :| let me see 

Ok bad news, the plugin is like 20 mb. Where should I upload it?

**Comment by faustinoaq** [comment]
Use this :point_right: https://nofile.io/ I just want to try your plugin :sweat_smile: 

I think we also can publish a pre-alpha release in this repository

BTW, How is going `intellij-crystal-scala` ? Do you like more Scala than Kotlin ?

**Comment by s5bug** [comment]
I'm liking how much easier it is to develop the plugin in Scala (in my opinion, as I'm not an experienced Kotlin user). Unfortunately between Pre-AP Eng, AP World, and Precalc I haven't had much programming time.

NoFile.io: https://nofile.io/f/OJw52ZWcxoH/intellij-crystal.zip

**Comment by faustinoaq** [comment]
![screenshot_20170912_060308](https://user-images.githubusercontent.com/3067335/30322731-0f5f1990-9780-11e7-8379-843c366c94f5.png)

Sorry but nofile.io is failing for me. (I waited for hours)

Try to share the file using dropbox or google drive or something similar please :sweat:

**Comment by faustinoaq** [comment]
I'm cleaning my issue list :sweat_smile:

I think we can provide a zip file in the future on https://github.com/crystal-lang-tools/intellij-crystal/releases

Reopen this if you want to
