### ISSUE TITLE
Join to Crystal Tools organization

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/intellij-crystal#3]
Hi @TsundereBug some Crystal community members have the idea of a [Crystal Tools organization](https://github.com/crystal-lang-tools) inspired by [Julia Editor Support organization](https://github.com/JuliaEditorSupport).

We are adding repositories for sublime, emacs, vim, vscode, atom, etc. All in one place well documented easy to follow, collaborate and maintain. :-)

If you accept the proposal of move your repo to [Crystal Tools organization](https://github.com/crystal-lang-tools) leave a message in [Gitter room](https://gitter.im/crystal-scry/Lobby?source=orgpage) first.

Thanks you for your Crystal support. 💓

**Comment by s5bug** [comment]
Hey @faustinoaq! My intellij-crystal is just a form of yours (for now). I've been putting off a Scala rewrite :) I would love to move but I don't know how :/

**Comment by faustinoaq** [comment]
@TsundereBug Hi!

You can send a message to [keplersj](https://github.com/keplersj) on [Gitter](https://gitter.im/crystal-scry/Lobby)

Also see: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by keplersj** [comment]
Lol. Hi @faustinoaq I was actually already admin of this org and was unsubscribed from notifications on it. This is going to get some tlc.
