### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/intellij-crystal#4]
Based on https://github.com/benoist/intellij-crystal/issues/1

I'm not designer but like to use SVG/Inkscape

![logo](http://i.imgur.com/UgzDlyp.png)

**Comment by s5bug** [comment]
In my opinion, seems too spiky, sparse, and monochromatic. Maybe add thicker polygons and more variations of richer purples? Otherwise, seems official.

**Comment by faustinoaq** [comment]
I'm not designer :sweat_smile: but I'll give you other alternatives :point_down:  

Same logo with diferent color (same purple for Github Crystal)

![logo4](https://user-images.githubusercontent.com/3067335/29408220-fa4845a4-830c-11e7-81d0-bd2b3275e8b1.png)

More designs:

![logo1](https://user-images.githubusercontent.com/3067335/29408207-f2ef1eb8-830c-11e7-8127-eaf1b6ff2ee1.png)

![logo2](https://user-images.githubusercontent.com/3067335/29408211-f60c5b2e-830c-11e7-8bb6-25e8d84b0215.png)

![logo3](https://user-images.githubusercontent.com/3067335/29408215-f803b8d2-830c-11e7-9024-6763e68ad5f1.png)

![logo5](https://user-images.githubusercontent.com/3067335/29408224-fc7eac1e-830c-11e7-980c-f869c02443f4.png)

The last one is bad, I know :laughing:

**Comment by faustinoaq** [comment]
Maybe we can use a logo as simple as this :point_down: 

![logo1](https://user-images.githubusercontent.com/3067335/29408337-6e1314b4-830d-11e7-9e2c-49bf8a1ee970.png)

Font: Roboto
Color: #635578 (same as Github)

**Comment by s5bug** [comment]
Yes, love that one :smile: I think it would look good for the plugin icon (hopefully they add customizable plugin icons instead of just the plug thing)

**Comment by faustinoaq** [comment]
Logo was added to readme :smile:
